### PR TITLE
Fix case insensitive address duplication bug

### LINKED ISSUE #181: [PE-D][Tester B] Duplication of address
Duplication of address can be achieved by adding the same place with different combination of small and capital letters.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: HT-T/ped#8

### PR DESCRIPTION
**Pull request by OVReader**
Fix #181

### CODE REVIEW

File: src/main/java/seedu/duke/parsermanager/ParseAddProperty.java [hunk 1]
```diff
@@ -267,7 +267,7 @@ private void checkForDuplicateProperty(PropertyList propertyList, String propert
 
     private boolean checkForDuplicateAddress(PropertyList propertyList, String propertyAddress) {
         for (Property property: propertyList.getPropertyList()) {
-            boolean isDuplicateAddress = property.getPropertyAddress().equals(propertyAddress);
+            boolean isDuplicateAddress = property.getPropertyAddress().equalsIgnoreCase(propertyAddress);
```
Comment (ngdeqi) [inline src/main/java/seedu/duke/parsermanager/ParseAddProperty.java:270]: Very elegant solution.

**Review by ngdeqi — COMMENTED** [review]
LGTM!

**Review by FeliciaBeatrice — APPROVED** [review]
LGTM!
