### PR TITLE
Fix a bug that deleted client/property can still be paired during loading

### LINKED ISSUE #136: Bug where Pairing is still made during loading phase despite client being deleted

### PR DESCRIPTION
**Pull request by wilsonngja**
Fix #136

### CODE REVIEW

**Review by FeliciaBeatrice — COMMENTED** [review]
everything looks good! LGTM

File: src/main/java/seedu/duke/Storage.java [hunk 1]
```diff
@@ -539,6 +539,9 @@ public void scanPairingFile(File pairFile) {
                     Property pairingProperty = new Property(landLordName, propertyAddress, rentalPrice, unitType);
 
                     if ((clientParameters.length == 4) && (propertyParameters.length == 4)) {
```
Comment (ngdeqi) [inline src/main/java/seedu/duke/Storage.java:541]: Do avoid magic literals

File: src/main/java/seedu/duke/Storage.java [hunk 2]
```diff
@@ -567,13 +570,17 @@ public void scanPairingFile(File pairFile) {
                             boolean isCorrectRental = propertyListRentalPrice.equals(rentalPrice);
                             boolean isCorrectUnitType = propertyListUnitType.equals(unitType);
 
-                            boolean isCorrectProperty = isCorrectLandlordName && isCorrectAddress
+                            isCorrectProperty = isCorrectLandlordName && isCorrectAddress
```
Comment (ngdeqi) [inline src/main/java/seedu/duke/Storage.java:573]: Good job breaking the statements down

**Review by ngdeqi — APPROVED** [review]
