### PR TITLE
Branch parser refactor

### LINKED ISSUE #74: Refactor Parser and Exceptions
More OOP and standardise exception types

### PR DESCRIPTION
**Pull request by ngdeqi**
Standardize exceptions, exception messages, parser methods, shorten Duke
Fixes #74

### CODE REVIEW

**Comment by wilsonngja** [comment]
Added assignees, milestone and labels to this issue.

File: src/main/java/seedu/duke/CommandStructure.java [hunk 1]
```diff
@@ -0,0 +1,24 @@
+package seedu.duke;
+
+public class CommandStructure {
+
```
Comment (FeliciaBeatrice) [inline src/main/java/seedu/duke/CommandStructure.java:4]: good use of constants instead of hard coded values

File: src/main/java/seedu/duke/Messages.java [hunk 2]
```diff
@@ -12,51 +18,50 @@ public class Messages {
...
 
-    public static final String MESSAGE_CLIENT_DELETED = "Deleting a client with the following information:";
+    public static final String MESSAGE_CLIENT_DELETED = "Deleting client with the following information:";
 
     public static final String MESSAGE_PAIRED = "Pairing the following client and property: ";
 
     public static final String MESSAGE_UNPAIRED = "Unpairing the following client and property: ";
 
 
-    /* Add Property/Client Related Error Messages */
```
Comment (FeliciaBeatrice) [inline src/main/java/seedu/duke/Messages.java:26]: good use of comments making the code look neater

**Review by FeliciaBeatrice — APPROVED** [review]
