### PR TITLE
Branch fix parser add discrepancies

### LINKED ISSUE #90: Inconsistent output for missing description for add operation
image

As shown in the image above, example was given for client but not for property. Would be good if can rectify this by making it more consistent.

### LINKED ISSUE #95: Missing Optional Email Feature for Add Client
The previously implemented add client allows client's email to be optional. However, this feature become a bug (exception triggered) when no email is provided by the user.

### PR DESCRIPTION
**Pull request by OVReader**
This branch attempts to fix the following issues (bugs) along with some coding violations
Fix #95
Fix #90

### CODE REVIEW

**Review by ngdeqi — COMMENTED** [review]
Follows all the code quality standards. LGTM

File: src/main/java/seedu/duke/parsermanager/ParseAddClient.java [hunk 1]
```diff
@@ -10,187 +10,158 @@
...
+        if (!hasValidEmail) {
             throw new InvalidEmailException(EXCEPTION);
         }
     }
 
     private void checkForBudgetNumberFormat(String budget) throws InvalidBudgetFormatException {
-        //Accepts only positive whole number
-        String regex = "^[1-9]\\d*$";
-        boolean hasValidBudgetNumberFormat = checkForDetailFormat(regex, budget);
+        boolean hasValidBudgetNumberFormat = checkForDetailFormat(VALID_BUDGET_REGEX, budget);
```
Comment (wilsonngja) [inline src/main/java/seedu/duke/parsermanager/ParseAddClient.java:162]: Good use of boolean variables

**Review by wilsonngja — APPROVED** [review]
Overall has good SLAP used and conforms to coding standard. LGTM
