### PR TITLE
Optimize add-related error messages

### LINKED ISSUE #177: [PE-D][Tester B] Address error when keying in "Singapore"
If "Singapore" is spelt wrongly, the error message displayed would still be "wrong address input". 

Although this is indeed a rare error which users are responsible with, it could be shortened to "S" when typing in the post code, eg. "S 118430", since this application is intended for Singapore use only.

Typing "Singapore" with typos, coupled with the "one-fit-for-all" error message, is surprisingly not easy to correct when everything is clumped together. 

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: HT-T/ped#4

### LINKED ISSUE #179: [PE-D][Tester B] Unclear error messages for address input
Inputs of this program are long and have to be precise. 

However, the error message is one-for-all, making it slightly harder for users to correct themselves. This issue is more prominent coupled with the fact that users cannot navigate left or right when typing in the terminal. They have to copy and paste the whole input again and again, until they are sure where the problem is.

Examples of possible separation of error messages:

- Post code does not match the address. Maybe there is a typo in your address?

- Post code does not exist in Singapore. 

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: HT-T/ped#6

### LINKED ISSUE #180: [PE-D][Tester B] Documentation of input of price/budget
It would be sufficient to say "please only input positive whole number / integer" in this case. 

"No letters/symbols" here may cause misunderstanding to some people who attempt to key in a float, as it is not very straightforward for people to link "no symbols" to "only integers".

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: HT-T/ped#7

### PR DESCRIPTION
**Pull request by OVReader**
Fix #180 (Error message for price/budget becomes more straightforward)
Fix #179 (Error message for address becomes more concise)
Fix #177 (Postal code requirement changes from `Singapore XXXXXX` to `SXXXXXX`, hence shorter validation and error messages)
Add some basic line separation for add-related outputs and general duke exceptions with regards to issue #174 (see code comment)

### CODE REVIEW

File: src/main/java/seedu/duke/Duke.java [hunk 1]
```diff
@@ -48,7 +48,12 @@ public void run() {
                 isCommandQuit = (command instanceof CommandQuit);
 
             } catch (DukeException e) {
+                // For issue #174
+                // Added some newline before and after exception message (Can try out to see what works best)
+                // Not done for Invalid Command Message
+                ui.printNewline();
```
Comment (wilsonngja) [inline src/main/java/seedu/duke/Duke.java:54]: Good use of UI methods.

File: src/main/java/seedu/duke/Messages.java [hunk 2]
```diff
@@ -8,6 +8,7 @@ public class Messages {
     public static final String EXCEPTION = "EXCEPTION";
     public static final String LINE_BREAK = "----------------------------------------------------------------------"
             + "----------";
+    public static final String INDENT = "        ";
```
Comment (wilsonngja) [inline src/main/java/seedu/duke/Messages.java:11]: Would it be better if you use "\t" instead?

File: src/main/java/seedu/duke/Messages.java [hunk 3]
```diff
@@ -77,21 +78,25 @@ public class Messages {
...
             + LINE_BREAK
-            + "\nBUILDINGS (e.g. HDBs, apartments, condominiums):\n"
-            + "  Format (Without Building Name):\n  [Block Number]<space>[Street Name]<space>"
-            + "#[Unit Level]-[Unit Number]{<space>[Building Name]},<space>Singapore<space>[Postal Code]\n"
-            + "  Example: 101 Marlow Street #12-05, Singapore 059020\n"
-            + "  Example (With Building Name): 101 Marlow Street #12-05 Clife Parkview, Singapore 059020\n"
+            + "\n  Example:\n"
+            + INDENT + "60 Aria Street, S602580\n"
+            + INDENT + "101 Marlow Street #12-05, S059020\n"
+            + INDENT + "101 Marlow Street #12-05 Clife Parkview, S059020\n"
```
Comment (wilsonngja) [inline src/main/java/seedu/duke/Messages.java:89]: I really like your extensive examples :D

**Review by wilsonngja — COMMENTED** [review]
Good job on optimising the error related messages. LGTM

File: src/main/java/seedu/duke/Ui.java [hunk 4]
```diff
@@ -71,6 +71,10 @@ public void showToUser(String message) {
         System.out.println(message);
     }
 
+    public void printNewline() {
+        System.out.print(System.lineSeparator());
+    }
```
Comment (ngdeqi) [inline src/main/java/seedu/duke/Ui.java:76]: Good use of SLAP

File: src/main/java/seedu/duke/Duke.java [hunk 5]
```diff
@@ -48,7 +48,12 @@ public void run() {
...
                 ui.showExceptionMessage(e);
+                ui.printNewline();
```
Comment (ngdeqi) [inline src/main/java/seedu/duke/Duke.java:56]: Good use of SLAP

**Review by ngdeqi — APPROVED** [review]
LGTM, no problems with code quality
