### PR TITLE
Fix coding standard violations for ParseAddProperty, Property and Client

### LINKED ISSUE #196: Code Review: @OVReader
@OVReader 
**src/main/java/seedu/duke/parsermanager/ParseAddProperty.java:**

image
image

image

1. Line 107: Variable names must be in camelCase
2. Line 74-85- Do not trip up the reader.
              While the comments indicate a particular grouping of regex, the actual regex constants seem mixed up - landed regex can be seen along with building, though there are seperate logical sections that follow.
3. Line 285: Comment Minimally but sufficiently: Maybe first part saying checks singapore address is redundant as it seems self explanatory from the function name

**src/main/java/seedu/duke/CommandStructure.java**

image
image

1. Line 41-50: Use name to explain - can consider naming as `UNIT_TYPE_2ROOM` and `UNIT_TYPE_EX_FLAT` and so on so the meaning is clear from the name itself.
2. Line 52-86: Similar to the above comment, use name to explain

**src/main/java/seedu/duke/Client.java**

image

1. Line 22-28: Avoid using magic strings

### PR DESCRIPTION
**Pull request by OVReader**
Fix #196

### CODE REVIEW

File: src/main/java/seedu/duke/Client.java [hunk 1]
```diff
@@ -19,13 +24,13 @@ public Client(String clientName, String clientContactNumber, String clientEmail,
     @Override
     public String toString() {
         StringBuilder clientDetails = new StringBuilder();
-        clientDetails.append("  Client: ").append(clientName).append(System.lineSeparator());
-        clientDetails.append("  Contact Number: ").append(clientContactNumber).append(System.lineSeparator());
+        clientDetails.append(CLIENT_LABEL).append(clientName).append(System.lineSeparator());
```
Comment (wilsonngja) [inline src/main/java/seedu/duke/Client.java:27]: Good use of meaningful name to replace strings to avoid magic strings.

File: src/main/java/seedu/duke/Property.java [hunk 2]
```diff
@@ -4,6 +4,11 @@
  * Represents a property.
  */
 public class Property {
+    public static final String LANDLORD_LABEL = "  Landlord: ";
+    public static final String ADDRESS_LABEL = "  Address: ";
+    public static final String PRICE_SGD_LABEL = "  Renting Price: SGD";
+    public static final String PER_MONTH_LABEL = "/month";
+    public static final String UNIT_TYPE_LABEL = "  Unit Type: ";
```
Comment (wilsonngja) [inline src/main/java/seedu/duke/Property.java:11]: I really like how your naming is short but self explanatory.

**Review by wilsonngja — COMMENTED** [review]
I really like the improvements you made to fix the standard violation. Good job. LGTM :D

File: src/main/java/seedu/duke/parsermanager/ParseAddProperty.java [hunk 3]
```diff
@@ -128,7 +129,7 @@ public ParseAddProperty(String addCommandDescription, PropertyList propertyList)
         unitTypeHashMap.put(UNIT_TYPE_LANDED_TERRENCE_SHORT, ACTUAL_UNIT_TYPE_LANDED_TERRENCE);
         unitTypeHashMap.put(UNIT_TYPE_SEMI_DETEACHED_SHORT, ACTUAL_UNIT_TYPE_SEMI_DETACHED);
         unitTypeHashMap.put(UNIT_TYPE_BUNGALOW_SHORT, ACTUAL_UNIT_TYPE_BUNGALOW);
-        UNIT_TYPE_HASHMAP = unitTypeHashMap;
+        unitTypeHashmap = unitTypeHashMap;
```
Comment (ngdeqi) [inline src/main/java/seedu/duke/parsermanager/ParseAddProperty.java:132]: This looks like the self assignment of a variable. Try not to trip up the reader

**Review by ngdeqi — APPROVED** [review]

**Review by FeliciaBeatrice — APPROVED** [review]
LGTM!
