### PR TITLE
Modify parse add related exceptions as class based exceptions

### LINKED ISSUE #142: ParseAdd - related exceptions are too unorganized

### PR DESCRIPTION
**Pull request by OVReader**
Fix #142 
Organize exceptions via class

### CODE REVIEW

File: src/main/java/seedu/duke/exception/InvalidBudgetFormatException.java [hunk 1]
```diff
@@ -1,12 +1,13 @@
...
 package seedu.duke.exception;
 
 import static seedu.duke.Messages.MESSAGE_INVALID_BUDGET_FORMAT;
 
-//@@author OVReader
 /**
  * Represents exception when incorrect format for budget is given when adding client.
  */
-public class InvalidBudgetFormatException extends DukeParseException {
+public class InvalidBudgetFormatException extends ParseAddClientException {
```
Comment (ngdeqi) [inline src/main/java/seedu/duke/exception/InvalidBudgetFormatException.java:10]: Good job using inheritance to classify the exceptions!

File: src/main/java/seedu/duke/parsermanager/ParseAddClient.java [hunk 2]
```diff
@@ -52,42 +54,40 @@ public ParseAddClient(String addCommandDescription, ClientList clientList) {
...
-            ArrayList<String> clientDetails = processCommandAddClientDetails(commandDescription);
-            validateClientDetails(clientDetails);
-            return new CommandAddClient(clientDetails);
-        } catch (EmptyDetailException e) {
-            throw new EmptyDetailException(MESSAGE_ADD_CLIENT_WRONG_FORMAT);
-        } catch (MissingFlagException e) {
-            throw new MissingFlagException(MESSAGE_ADD_CLIENT_WRONG_FORMAT);
-        } catch (IncorrectFlagOrderException e) {
-            throw new IncorrectFlagOrderException(MESSAGE_ADD_CLIENT_WRONG_FORMAT);
+    public Command parseCommand() throws ParseAddClientException {
```
Comment (ngdeqi) [inline src/main/java/seedu/duke/parsermanager/ParseAddClient.java:57]: I like how you used substitutability to avoid making the throws declaration too long

File: src/main/java/seedu/duke/parsermanager/ParseAddProperty.java [hunk 3]
```diff
@@ -268,6 +276,6 @@ private boolean checkForDuplicateAddress(PropertyList propertyList, String prope
 
     private static void showExistingDuplicateProperty(Property property) {
         Ui ui = new Ui();
-        ui.showToUser("Existing Property:\n  " + property.toString());
+        ui.showToUser(EXISTING_PROPERTY + property.toString());
```
Comment (ngdeqi) [inline src/main/java/seedu/duke/parsermanager/ParseAddProperty.java:279]: Good job converting magic literals to constant variables!

File: src/main/java/seedu/duke/parsermanager/Parser.java [hunk 4]
```diff
@@ -13,6 +13,12 @@ public abstract class Parser {
     protected static final int UNIT_VALUE = 1;
 
     public abstract Command parseCommand() throws DukeException;
+    /**
+     *  Will be removed after everyone has created local checkForEmptyDetails method
+     *  (e.g. checkForDeleteClientDetails, checkForPairDetails, etc)
+     *  Local method will call common method isEmptyString() (below) and throw local exceptions
+     *  (e.g. EmptyDeleteClientDetailException, EmptyPairDetailException, etc)
+     */
```
Comment (ngdeqi) [inline src/main/java/seedu/duke/parsermanager/Parser.java:21]: thanks for the heads up

File: src/main/java/seedu/duke/command/CommandAddProperty.java [hunk 5]
```diff
@@ -1,3 +1,5 @@
+//@@author OVReader
```
Comment (wilsonngja) [inline src/main/java/seedu/duke/command/CommandAddProperty.java:1]: From what I remember, the first line should always be package. 
You might want to check back in your code if there is any warnings or errors.

File: src/main/java/seedu/duke/exception/EmptyAddClientDetailException.java [hunk 6]
```diff
@@ -0,0 +1,15 @@
+//@@author OVReader
+
+package seedu.duke.exception;
+
+import static seedu.duke.Messages.MESSAGE_ADD_CLIENT_WRONG_FORMAT;
+
+/**
+ * Represents exception when no client description is provided when adding client.
```
Comment (wilsonngja) [inline src/main/java/seedu/duke/exception/EmptyAddClientDetailException.java:8]: Good job in explaining when the exception is being thrown.

File: src/main/java/seedu/duke/parsermanager/ParseAddProperty.java (hunk 3 above)
Comment (wilsonngja) [inline src/main/java/seedu/duke/parsermanager/ParseAddProperty.java:279]: Good job in constantly avoiding the magic literals.

File: src/main/java/seedu/duke/parsermanager/ParseAddProperty.java [hunk 7]
```diff
@@ -129,45 +131,51 @@ public ParseAddProperty(String addCommandDescription, PropertyList propertyList)
...
             checkForCorrectFlagOrder(flagIndexPositions[flagIndex], flagIndexPositions[flagIndex + UNIT_VALUE]);
         }
     }
 
+    private void checkForCorrectFlagOrder(int flagPosition, int nextFlagPosition) throws
+            IncorrectAddPropertyFlagOrderException {
+        boolean hasCorrectOrder = (flagPosition < nextFlagPosition);
+        if (!hasCorrectOrder) {
+            throw new IncorrectAddPropertyFlagOrderException();
+        }
```
Comment (wilsonngja) [inline src/main/java/seedu/duke/parsermanager/ParseAddProperty.java:176]: Good exception throwing here. I really like how your exception is really helpful in avoiding runtime errors.

**Review by wilsonngja — APPROVED** [review]
Overall, great job. Thanks for initiating the exception to class based. 
Good job in complying to the standards too. LGTM
