### PR TITLE
Branch storage unit type bug

### LINKED ISSUE #127: Loading Unit-Type from storage bug
There is a bug when unit-type loads from storage after the implementation of unit-type validation

### PR DESCRIPTION
**Pull request by wilsonngja**
Fix #127

### CODE REVIEW

File: src/main/java/seedu/duke/Storage.java [hunk 1]
```diff
@@ -210,15 +261,17 @@ public void loadProperty(File propertyFile) {
                     String landlordName = propertyParameters[0];
                     String address = propertyParameters[1];
                     String price = propertyParameters[2];
-                    String unitType = propertyParameters[3].trim();
+                    String unitTypeString = propertyParameters[3].trim();
```
Comment (ngdeqi) [inline src/main/java/seedu/duke/Storage.java:264]: Do avoid magic literals

File: src/main/java/seedu/duke/Storage.java [hunk 2]
```diff
@@ -210,15 +261,17 @@ public void loadProperty(File propertyFile) {
...
-                            + PROPERTY_RENTAL_FLAG + price + PROPERTY_TYPE_FLAG + unitType;
+                            + PROPERTY_RENTAL_FLAG + price + PROPERTY_TYPE_FLAG + unitTypeLabel;
 
                     ParseAddProperty parser = new ParseAddProperty(description, propertyList);
                     try {
                         parser.parseCommand();
-                        propertyList.addProperty(landlordName, address, price, unitType);
+                        propertyList.addProperty(landlordName, address, price, unitTypeLabel);
                     } catch (DukeException e) {
                         System.out.println(Messages.INVALID_PROPERTY_FILE);
```
Comment (ngdeqi) [inline src/main/java/seedu/duke/Storage.java:276]: Maybe you could use the ui class to print the error message

**Review by OVReader — APPROVED** [review]
LGTM
