### PR TITLE
List coding violations fix

### LINKED ISSUE #202: Code Review: @zoranabc201
@zoranabc201 
**src/main/java/seedu/duke/command/CommandListPropertiesWithTags.java**:
image

1. Line 38: Use the default branch - to detect errors if there is no default action

**src/main/java/seedu/duke/parsermanager/ParseListProperty.java**
image
1. Line 38: Remember to indent the comment relative to the position of the code.

**src/main/java/seedu/duke/Ui.java**
image
1. Lines 265,267, 273, 275 Avoid magic strings

### PR DESCRIPTION
**Pull request by zoranabc201**

### CODE REVIEW

File: src/main/java/seedu/duke/command/CommandListClients.java [hunk 1]
```diff
@@ -1,18 +1,24 @@
...
 import seedu.duke.Storage;
 import seedu.duke.Ui;
 
 public class CommandListClients extends Command {
+
+    @Override
     public void execute(Ui ui, Storage storage, PropertyList propertyList, ClientList clientList,
                         PairingList pairingList) {
-        for (int i = 0; i < clientList.getCurrentListSize(); i++) {
+        for (int i = CommandStructure.START_INDEX; i < clientList.getCurrentListSize(); i++) {
```
Comment (ngdeqi) [inline src/main/java/seedu/duke/command/CommandListClients.java:15]: I find
 ```
for (Client client : clientList.getClientList()) {}
``` 
very useful for iterating through lists.

File: src/main/java/seedu/duke/Ui.java [hunk 2]
```diff
@@ -300,27 +309,27 @@ public void displayOnePropertyShort(Property property, int i) {
...
 
-    public void displayNoOfProperties(int i) {
-        if (i == 1) {
-            System.out.println("There is " + i + " property in the list");
+    public void displayNoOfProperties(int i, boolean isOneProperty) {
+        if (isOneProperty) {
+            System.out.println(THERE_IS + i + PROPERTY_SINGULAR + IN_THIS_LIST);
         } else {
-            System.out.println("There are " + i + " properties in this list");
+            System.out.println(THERE_ARE + i + PROPERTIES_PLURAL + IN_THIS_LIST);
```
Comment (ngdeqi) [inline src/main/java/seedu/duke/Ui.java:316]: You could try changing the message to have an optional 's', e.g. client(s) ,so that you don't need extra code to handle plural and singular list results

**Review by ngdeqi — COMMENTED** [review]
LGTM

File: src/main/java/seedu/duke/Ui.java [hunk 3]
```diff
@@ -300,27 +309,27 @@ public void displayOnePropertyShort(Property property, int i) {
...
         }
     }
 
-    public void displayNoOfClients(int i) {
-        if (i == 1) {
-            System.out.println("There is " + i + " client in the list");
+    public void displayNoOfClients(int i, boolean isOneClient) {
+        if (isOneClient) {
+            System.out.println(THERE_IS + i + CLIENT_SINGULAR + IN_THIS_LIST);
```
Comment (wilsonngja) [inline src/main/java/seedu/duke/Ui.java:322]: You can consider using the Ui method to display the text.

File: src/main/java/seedu/duke/command/CommandListClientsWithTags.java [hunk 4]
```diff
@@ -34,43 +41,51 @@ public void execute(Ui ui, Storage storage, PropertyList propertyList, ClientLis
             displayClientShort(clientList, ui);
             break;
         default:
+            //no errors are possible at this stage. Any potential errors are handled earlier
```
Comment (wilsonngja) [inline src/main/java/seedu/duke/command/CommandListClientsWithTags.java:44]: This is in relation to line 32 and line 35. I am not able to comment on that line as it was not in the current code change.

For the method `displayClientNames` and `displayClientEmails`, since it's displaying 1 name and 1 email, I think there's a grammatical error. 

Sorry for missing it out.

File: src/main/java/seedu/duke/command/CommandListClientsWithTags.java [hunk 5]
```diff
@@ -34,43 +41,51 @@ public void execute(Ui ui, Storage storage, PropertyList propertyList, ClientLis
...
     }
 
     private void displayClientContacts(ClientList clientList, Ui ui) {
-        for (int i = 0; i < clientList.getCurrentListSize(); i++) {
+        for (int i = CommandStructure.START_INDEX; i < clientList.getCurrentListSize(); i++) {
             ui.displayOneClientContact(clientList.getClientList().get(i), i + 1);
         }
-        ui.displayNoOfClients(clientList.getCurrentListSize());
+        ui.displayNoOfClients(clientList.getCurrentListSize(),
+                clientList.getCurrentListSize() == CommandStructure.ONE_ITEM_IN_LIST);
```
Comment (wilsonngja) [inline src/main/java/seedu/duke/command/CommandListClientsWithTags.java:56]: Would it be better to assign a boolean variable to `clientList.getCurrentListSize() == CommandStructure.ONE_ITEM_IN_LIST` and use that variable to pass into the method?

File: src/main/java/seedu/duke/parsermanager/ParserManager.java [hunk 6]
```diff
@@ -142,12 +142,15 @@ private Parser parseListCommand(String commandDetail) throws UndefinedSubCommand
         boolean isListProperty = listCommandTypeAndFlags.get(0).trim().equals(PROPERTY_FLAG);
         boolean isListClient = listCommandTypeAndFlags.get(0).equals(CLIENT_FLAG);
         boolean isListEverything = listCommandTypeAndFlags.get(0).equals(EVERYTHING_FLAG);
+        boolean isListPairs = listCommandTypeAndFlags.get(0).equals(PAIR_FLAG);
```
Comment (wilsonngja) [inline src/main/java/seedu/duke/parsermanager/ParserManager.java:145]: Would it be better to replace the '0' here to a meaningful name to help the reader improve their understanding of the code?

**Review by wilsonngja — APPROVED** [review]
Thanks for the improvements made. The code LGTM.
Some of the suggestion are as follows:
- Can consider changing all the parameter passing into the method into a boolean variable to help the reader improve their understanding of the code.
- Can replace magic numbers with a meaningful name.
